// <auto-generated />
using System;
using ICMS.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302164020_FixAutoGeneratedCardNumber")]
    partial class FixAutoGeneratedCardNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BatchId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CookNumber")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DoseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.HasIndex("UserId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DoseId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("character varying(150)");

                    b.Property<byte>("DoseOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecommendedAgeGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RecommendedAgeInMonths")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoseName")
                        .IsUnique();

                    b.HasIndex("VaccineId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.DoseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DoseReportId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DoseReports");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FieldVisitId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TargetedLocation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("FieldVisits");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisitUser", b =>
                {
                    b.Property<int>("FieldVisitId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FieldVisitId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FieldVisitUsers");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.HealthAdvisory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HealthAdvisoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthAdvisories");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.ImmunizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ImmunizationRecordId");

                    b.Property<int>("DoseId")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldVisitId")
                        .HasColumnType("integer");

                    b.Property<int>("IndividualId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TakenIn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("VaccinationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.HasIndex("FieldVisitId");

                    b.HasIndex("IndividualId");

                    b.HasIndex("IndividualId", "DoseId")
                        .IsUnique();

                    b.ToTable("ImmunizationRecords");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.Newborn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NewbornId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NewbornGender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewbornStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NewbornWeightInGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PregnancyDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailsId");

                    b.ToTable("Newborns");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PersonId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "FirstName", "LastName", "DateOfBirth")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PregnancyDetailsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthLocationDetails")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BirthLocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthNature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthNatureReason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ComplicationsDuringChildbirth")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Interferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPregnancyDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("LastMenstrualPeriodDate")
                        .HasColumnType("date");

                    b.Property<byte>("NewbornCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("PostpartumComplications")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PregnancyComplications")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PregnancyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PregnantWomanId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPostartumComplicationsId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPregnancyComplicationsId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPregnancyDeliveryComplicationsId")
                        .HasColumnType("integer");

                    b.Property<byte>("VisitsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("PregnantWomanId");

                    b.HasIndex("PreviousPostartumComplicationsId")
                        .IsUnique();

                    b.HasIndex("PreviousPregnancyComplicationsId")
                        .IsUnique();

                    b.HasIndex("PreviousPregnancyDeliveryComplicationsId")
                        .IsUnique();

                    b.ToTable("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PregnantWomanId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<byte>("PregnancyCount")
                        .HasColumnType("smallint");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PersonId", "UserId" }, "IX_VaccinatedIndividuals_People_Users");

                    b.ToTable("PregnantWomen");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPostartumComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("NeonatalDeathWithinFirstWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PlacentaRetention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("PuerperalSepsis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalBleeding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalFistula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPostpartumComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPregnancyComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Diabetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Epilepsy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HeartDisease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Preeclampsia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("PretermBirthBefore8Months")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RecurrentMiscarriageMoreThanThree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalBleedingDuringPregnancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPregnancyComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPregnancyDeliveryComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssistedDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CesareanSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("StillbirthOrMultipleDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPregnancyDeliveryComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Audit.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceorDestination")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VaccinatedIndividualId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValueSql("'AB' || LPAD(nextval('public.cardnumber_sequence')::text, 6, '0')");

                    b.Property<string>("Directorate")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "PersonId", "UserId" }, "IX_VaccinatedIndividuals_People_Users")
                        .HasDatabaseName("IX_VaccinatedIndividuals_People_Users1");

                    b.ToTable("VaccinatedIndividuals");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VaccineId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .IsUnicode(true)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<byte>("TotalDosages")
                        .HasColumnType("smallint");

                    b.Property<string>("VaccineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("VaccineCode")
                        .IsUnique();

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.VisitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VisitDetailsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("APPInUrineTest")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AnaemiaOrHemoglobinType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ClinicalExaminationAndObservation")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FetalHeartbeat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FetalMovement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FetalPosition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("LegsSwelling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("NextVisitDate")
                        .HasColumnType("date");

                    b.Property<string>("OGTTInUrineTest")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PregnancyDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("PregnancyDurationInWeeks")
                        .HasColumnType("integer");

                    b.Property<byte>("TetanusDoseNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<bool>("VaginalBleeding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("VisitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'utc')::date");

                    b.Property<decimal>("WeightInKilo")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailsId");

                    b.ToTable("VisitDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dose");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Dose", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Vaccine", "Vaccine")
                        .WithMany("Doses")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.DoseReport", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Batch", "Batch")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Clinical.DoseReport", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisitUser", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Visits.FieldVisit", "FieldVisit")
                        .WithMany("FieldVisitUsers")
                        .HasForeignKey("FieldVisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "FieldWorker")
                        .WithMany("FieldVisitUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldVisit");

                    b.Navigation("FieldWorker");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.HealthAdvisory", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.ImmunizationRecord", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Visits.FieldVisit", "FieldVisit")
                        .WithMany("ImmunizationRecords")
                        .HasForeignKey("FieldVisitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "VaccinatedIndividual")
                        .WithMany("ImmunizationRecords")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dose");

                    b.Navigation("FieldVisit");

                    b.Navigation("VaccinatedIndividual");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.Newborn", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithMany()
                        .HasForeignKey("PregnancyDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnantWoman", "PregnantWoman")
                        .WithMany("PregnancyDetails")
                        .HasForeignKey("PregnantWomanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnantWoman");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPostpartumComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPregnancyComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPregnancyDelivaryComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.RefreshToken", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Audit.Transaction", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Batch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Identity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.UserRole", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.VisitDetails", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithMany("VisitDetails")
                        .HasForeignKey("PregnancyDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisit", b =>
                {
                    b.Navigation("FieldVisitUsers");

                    b.Navigation("ImmunizationRecords");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.Navigation("PreviousPostpartumComplications");

                    b.Navigation("PreviousPregnancyComplications");

                    b.Navigation("PreviousPregnancyDelivaryComplications");

                    b.Navigation("VisitDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.Navigation("FieldVisitUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.Navigation("ImmunizationRecords");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Vaccine", b =>
                {
                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
