// <auto-generated />
using System;
using ICMS.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICMS.Domain.Entites.Audit.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceorDestination")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BatchId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CookNumber")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DoseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.HasIndex("UserId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DoseId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("character varying(150)");

                    b.Property<byte>("DoseOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecommendedAgeGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RecommendedAgeInMonths")
                        .HasColumnType("integer");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoseName")
                        .IsUnique();

                    b.HasIndex("VaccineId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.DoseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DoseReportId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DoseReports");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.HealthAdvisory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HealthAdvisoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthAdvisories");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.ImmunizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ImmunizationRecordId");

                    b.Property<int>("DoseId")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldVisitId")
                        .HasColumnType("integer");

                    b.Property<int>("IndividualId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TakenIn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("VaccinationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.HasIndex("FieldVisitId");

                    b.HasIndex("IndividualId");

                    b.HasIndex("IndividualId", "DoseId")
                        .IsUnique();

                    b.ToTable("ImmunizationRecords");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.VaccinationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VaccinationScheduleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date");

                    b.Property<int>("DoseId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImmunizationRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VaccinatedIndividualId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.HasIndex("ImmunizationRecordId")
                        .IsUnique();

                    b.HasIndex("VaccinatedIndividualId");

                    b.ToTable("VaccinationSchedules");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VaccineId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .IsUnicode(true)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<byte>("TotalDosages")
                        .HasColumnType("smallint");

                    b.Property<string>("VaccineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("VaccineCode")
                        .IsUnique();

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Directorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernorateId = 22,
                            Name = "السبعين"
                        },
                        new
                        {
                            Id = 2,
                            GovernorateId = 22,
                            Name = "الوحدة"
                        },
                        new
                        {
                            Id = 3,
                            GovernorateId = 22,
                            Name = "التحرير"
                        },
                        new
                        {
                            Id = 4,
                            GovernorateId = 22,
                            Name = "معين"
                        },
                        new
                        {
                            Id = 5,
                            GovernorateId = 22,
                            Name = "الصافية"
                        },
                        new
                        {
                            Id = 6,
                            GovernorateId = 22,
                            Name = "آزال"
                        },
                        new
                        {
                            Id = 7,
                            GovernorateId = 22,
                            Name = "صنعاء القديمة"
                        },
                        new
                        {
                            Id = 8,
                            GovernorateId = 22,
                            Name = "شعوب"
                        },
                        new
                        {
                            Id = 9,
                            GovernorateId = 22,
                            Name = "الثورة"
                        },
                        new
                        {
                            Id = 10,
                            GovernorateId = 22,
                            Name = "بني الحارث"
                        },
                        new
                        {
                            Id = 11,
                            GovernorateId = 5,
                            Name = "مدينة المكلا"
                        },
                        new
                        {
                            Id = 12,
                            GovernorateId = 5,
                            Name = "أرياف المكلا"
                        },
                        new
                        {
                            Id = 13,
                            GovernorateId = 5,
                            Name = "الشحر"
                        },
                        new
                        {
                            Id = 14,
                            GovernorateId = 5,
                            Name = "سيئون"
                        },
                        new
                        {
                            Id = 15,
                            GovernorateId = 5,
                            Name = "غيل باوزير"
                        });
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "صنعاء"
                        },
                        new
                        {
                            Id = 2,
                            Name = "عدن"
                        },
                        new
                        {
                            Id = 3,
                            Name = "تعز"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الحديدة"
                        },
                        new
                        {
                            Id = 5,
                            Name = "حضرموت"
                        },
                        new
                        {
                            Id = 6,
                            Name = "إب"
                        },
                        new
                        {
                            Id = 7,
                            Name = "أبين"
                        },
                        new
                        {
                            Id = 8,
                            Name = "البيضاء"
                        },
                        new
                        {
                            Id = 9,
                            Name = "لحج"
                        },
                        new
                        {
                            Id = 10,
                            Name = "مأرب"
                        },
                        new
                        {
                            Id = 11,
                            Name = "شبوة"
                        },
                        new
                        {
                            Id = 12,
                            Name = "الجوف"
                        },
                        new
                        {
                            Id = 13,
                            Name = "المهرة"
                        },
                        new
                        {
                            Id = 14,
                            Name = "المحويت"
                        },
                        new
                        {
                            Id = 15,
                            Name = "صعدة"
                        },
                        new
                        {
                            Id = 16,
                            Name = "حجة"
                        },
                        new
                        {
                            Id = 17,
                            Name = "الضالع"
                        },
                        new
                        {
                            Id = 18,
                            Name = "عمران"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ذمار"
                        },
                        new
                        {
                            Id = 20,
                            Name = "ريمة"
                        },
                        new
                        {
                            Id = 21,
                            Name = "سقطرى"
                        },
                        new
                        {
                            Id = 22,
                            Name = "أمانة العاصمة"
                        });
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.ToTable("Neighborhoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorateId = 1,
                            Name = "فوة-المتضررين"
                        },
                        new
                        {
                            Id = 2,
                            DirectorateId = 1,
                            Name = "فوة-ابن سيناء"
                        },
                        new
                        {
                            Id = 3,
                            DirectorateId = 1,
                            Name = "فوة-المساكن"
                        },
                        new
                        {
                            Id = 4,
                            DirectorateId = 1,
                            Name = "فوة-الإنشاءات"
                        },
                        new
                        {
                            Id = 5,
                            DirectorateId = 1,
                            Name = "فوة-القديمة"
                        },
                        new
                        {
                            Id = 6,
                            DirectorateId = 1,
                            Name = "الشرج-حي العمال"
                        },
                        new
                        {
                            Id = 7,
                            DirectorateId = 1,
                            Name = "الشرج-باعبود"
                        },
                        new
                        {
                            Id = 8,
                            DirectorateId = 1,
                            Name = "الشرج-المنورة"
                        },
                        new
                        {
                            Id = 9,
                            DirectorateId = 1,
                            Name = "الشرج-حي أكتوبر"
                        },
                        new
                        {
                            Id = 10,
                            DirectorateId = 1,
                            Name = "الديس-شعب البادية"
                        },
                        new
                        {
                            Id = 11,
                            DirectorateId = 1,
                            Name = "الديس-الغويزي"
                        },
                        new
                        {
                            Id = 12,
                            DirectorateId = 1,
                            Name = "الديس-حي 14 أكتوبر"
                        },
                        new
                        {
                            Id = 13,
                            DirectorateId = 1,
                            Name = "الديس-جول الشفاء"
                        },
                        new
                        {
                            Id = 14,
                            DirectorateId = 1,
                            Name = "المكلا-حي الشهيد"
                        },
                        new
                        {
                            Id = 15,
                            DirectorateId = 1,
                            Name = "المكلا-حي السلام"
                        },
                        new
                        {
                            Id = 16,
                            DirectorateId = 1,
                            Name = "المكلا-حي الصيادين"
                        });
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.SubNeighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("SubNeighborhoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "المتضررين-وحدة الصديق",
                            NeighborhoodId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "المتضررين-وحدة الربوة",
                            NeighborhoodId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "المتضررين-المنطقة المرتفعة",
                            NeighborhoodId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "ابن سيناء-مربع السكن الجامعي",
                            NeighborhoodId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "ابن سيناء-حي الكوادر",
                            NeighborhoodId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "ابن سيناء-منطقة المستشفى",
                            NeighborhoodId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "حي العمال-مربع الورش",
                            NeighborhoodId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "حي العمال-عمارة باجرش",
                            NeighborhoodId = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "شعب البادية-حارة الروضة",
                            NeighborhoodId = 10
                        },
                        new
                        {
                            Id = 10,
                            Name = "شعب البادية-جول الغليلة",
                            NeighborhoodId = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "حي الشهيد-سكة يعقوب",
                            NeighborhoodId = 14
                        },
                        new
                        {
                            Id = 12,
                            Name = "حي الشهيد-حارة البلاد",
                            NeighborhoodId = 14
                        },
                        new
                        {
                            Id = 13,
                            Name = "حي السلام-خلف البريد",
                            NeighborhoodId = 15
                        });
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PersonId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("TIMEZONE('utc', NOW())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "FirstName", "LastName", "DateOfBirth")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VaccinatedIndividualId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("character varying(60)")
                        .HasDefaultValueSql("'AB' || LPAD(nextval('public.cardnumber_sequence')::text, 6, '0')");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("integer");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubNeighborhoodId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "PersonId", "UserId" }, "IX_VaccinatedIndividuals_People_Users");

                    b.ToTable("VaccinatedIndividuals");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.Newborn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NewbornId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NewbornGender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewbornStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NewbornWeightInGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PregnancyDetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailsId");

                    b.ToTable("Newborns");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PregnancyDetailsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthLocationDetails")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BirthLocationType")
                        .HasColumnType("text");

                    b.Property<string>("BirthNature")
                        .HasColumnType("text");

                    b.Property<string>("BirthNatureReason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ComplicationsDuringChildbirth")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Interferences")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPregnancyDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("LastMenstrualPeriodDate")
                        .HasColumnType("date");

                    b.Property<byte>("NewbornCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("PostpartumComplications")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PregnancyComplications")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PregnancyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PregnantWomanId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPostpartumComplicationsId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPregnancyComplicationsId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousPregnancyDeliveryComplicationsId")
                        .HasColumnType("integer");

                    b.Property<byte>("VisitsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("PregnantWomanId");

                    b.HasIndex("PreviousPostpartumComplicationsId")
                        .IsUnique();

                    b.HasIndex("PreviousPregnancyComplicationsId")
                        .IsUnique();

                    b.HasIndex("PreviousPregnancyDeliveryComplicationsId")
                        .IsUnique();

                    b.ToTable("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PregnantWomanId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<byte>("PregnancyCount")
                        .HasColumnType("smallint");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "PersonId", "UserId" }, "IX_PregnantWomen_People_Users");

                    b.ToTable("PregnantWomen");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPostpartumComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("NeonatalDeathWithinFirstWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PlacentaRetention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("PuerperalSepsis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalBleeding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalFistula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPostpartumComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPregnancyComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Diabetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Epilepsy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HeartDisease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Preeclampsia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("PretermBirthBefore8Months")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RecurrentMiscarriageMoreThanThree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("VaginalBleedingDuringPregnancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPregnancyComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PreviousPregnancyDeliveryComplicationsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssistedDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CesareanSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PregnancyDetailId")
                        .HasColumnType("integer");

                    b.Property<bool>("StillbirthOrMultipleDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailId")
                        .IsUnique();

                    b.ToTable("PreviousPregnancyDeliveryComplications");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FieldVisitId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TargetedLocation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("FieldVisits");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisitUser", b =>
                {
                    b.Property<int>("FieldVisitId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FieldVisitId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FieldVisitUsers");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.VisitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VisitDetailsId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("APPInUrineTest")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AnaemiaOrHemoglobinType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ClinicalExaminationAndObservation")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FetalHeartbeat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FetalMovement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FetalPosition")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("LegsSwelling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("NextVisitDate")
                        .HasColumnType("date");

                    b.Property<string>("OGTTInUrineTest")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PregnancyDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("PregnancyDurationInWeeks")
                        .HasColumnType("integer");

                    b.Property<bool>("VaginalBleeding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("VisitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(NOW() AT TIME ZONE 'utc')::date");

                    b.Property<decimal>("WeightInKilo")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("PregnancyDetailsId");

                    b.ToTable("VisitDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Audit.Transaction", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Batch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dose");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Dose", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Vaccine", "Vaccine")
                        .WithMany("Doses")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.DoseReport", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Batch", "Batch")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Clinical.DoseReport", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.HealthAdvisory", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.ImmunizationRecord", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Visits.FieldVisit", "FieldVisit")
                        .WithMany("ImmunizationRecords")
                        .HasForeignKey("FieldVisitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "VaccinatedIndividual")
                        .WithMany("ImmunizationRecords")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dose");

                    b.Navigation("FieldVisit");

                    b.Navigation("VaccinatedIndividual");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.VaccinationSchedule", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Clinical.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Clinical.ImmunizationRecord", "ImmunizationRecord")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Clinical.VaccinationSchedule", "ImmunizationRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "VaccinatedIndividual")
                        .WithMany("Schedules")
                        .HasForeignKey("VaccinatedIndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dose");

                    b.Navigation("ImmunizationRecord");

                    b.Navigation("VaccinatedIndividual");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Directorate", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Geography.Governorate", "Governorate")
                        .WithMany("Directorates")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Neighborhood", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Geography.Directorate", "Directorate")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directorate");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.SubNeighborhood", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Geography.Neighborhood", "Neighborhood")
                        .WithMany("SubNeighborhoods")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Neighborhood");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.RefreshToken", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Identity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.UserRole", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Identity.VaccinatedIndividual", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.Newborn", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithMany("Newborns")
                        .HasForeignKey("PregnancyDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnantWoman", "PregnantWoman")
                        .WithMany("PregnancyDetails")
                        .HasForeignKey("PregnantWomanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnantWoman");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PregnantWoman", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PregnantWoman", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPostpartumComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPostpartumComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPregnancyComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPregnancyComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithOne("PreviousPregnancyDeliveryComplications")
                        .HasForeignKey("ICMS.Domain.Entites.Maternal.PreviousPregnancyDeliveryComplications", "PregnancyDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisitUser", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Visits.FieldVisit", "FieldVisit")
                        .WithMany("FieldVisitUsers")
                        .HasForeignKey("FieldVisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ICMS.Domain.Entites.Identity.User", "FieldWorker")
                        .WithMany("FieldVisitUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldVisit");

                    b.Navigation("FieldWorker");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.VisitDetails", b =>
                {
                    b.HasOne("ICMS.Domain.Entites.Maternal.PregnancyDetails", "PregnancyDetails")
                        .WithMany("VisitDetails")
                        .HasForeignKey("PregnancyDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Batch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Clinical.Vaccine", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Directorate", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Governorate", b =>
                {
                    b.Navigation("Directorates");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Geography.Neighborhood", b =>
                {
                    b.Navigation("SubNeighborhoods");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.User", b =>
                {
                    b.Navigation("FieldVisitUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Identity.VaccinatedIndividual", b =>
                {
                    b.Navigation("ImmunizationRecords");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnancyDetails", b =>
                {
                    b.Navigation("Newborns");

                    b.Navigation("PreviousPostpartumComplications");

                    b.Navigation("PreviousPregnancyComplications");

                    b.Navigation("PreviousPregnancyDeliveryComplications");

                    b.Navigation("VisitDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Maternal.PregnantWoman", b =>
                {
                    b.Navigation("PregnancyDetails");
                });

            modelBuilder.Entity("ICMS.Domain.Entites.Visits.FieldVisit", b =>
                {
                    b.Navigation("FieldVisitUsers");

                    b.Navigation("ImmunizationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
