using ICMS.Application.DTOs.Reports;
using System.Text;

namespace ICMS.Infrastructure.Reports.Templates
{
    /// <summary>
    /// Shared HTML rendering helper used by all report template renderers.
    /// Provides a professional, print-ready layout with ICMS branding.
    /// </summary>
    public static class ReportHtmlBase
    {
        public static string Wrap(string accentColor, string reportTitle, string iconEmoji, ReportData data, string bodyContent)
        {
            var isAr = data.Lang.StartsWith("ar", StringComparison.OrdinalIgnoreCase);
            var summaryHtml = BuildSummaryCards(data.SummaryStats, accentColor, isAr ? "الملخص الإحصائي" : "Summary Statistics");
            var dir  = isAr ? "rtl" : "ltr";
            var fontUrl = isAr
                ? "https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700&display=swap"
                : "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap";
            var fontFamily = isAr ? "'Cairo', sans-serif" : "'Inter', sans-serif";

            // Show a single date for daily reports; a range for multi-day reports
            var periodDisplay = data.StartDate == data.EndDate
                ? data.StartDate.ToString("yyyy-MM-dd")
                : $"{data.StartDate:yyyy-MM-dd} → {data.EndDate:yyyy-MM-dd}";

            var lblPeriod  = isAr ? "فترة التقرير"  : "Report Period";
            var lblRecords = isAr ? "إجمالي السجلات" : "Total Records";
            var lblGenAt   = isAr ? "وقت الإنشاء"   : "Generated At";
            var lblOfficial = isAr ? "تقرير رسمي" : "Official Report";
            var lblFooter  = isAr ? "أُنشئ تلقائياً بواسطة ICMS" : "Automatically generated by ICMS";

            var statsBar = $@"
                <div class='stats-footer-bar'>
                    <div class='stat-item'><span class='stat-label'>{lblPeriod}</span><span class='stat-value'>{periodDisplay}</span></div>
                    <div class='stat-item'><span class='stat-label'>{lblRecords}</span><span class='stat-value'>{data.TotalRecords}</span></div>
                    <div class='stat-item'><span class='stat-label'>{lblGenAt}</span><span class='stat-value'>{data.GeneratedAt}</span></div>
                </div>";

            return $@"<!DOCTYPE html>
<html lang='{data.Lang}' dir='{dir}'>
<head>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0'>
<title>{reportTitle} — ICMS Report</title>
<style>
  @import url('{fontUrl}');

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: {fontFamily}; background: #fff; color: #1e2a3b; font-size: 11px; line-height: 1.5; }}
  .page {{ max-width: 1000px; margin: 0 auto; padding: 40px; }}

  /* ── Header ── */
  .header {{ border-bottom: 2.5px solid {accentColor}; padding-bottom: 20px; margin-bottom: 30px;
             display: flex; align-items: center; gap: 25px; }}
  .header-icon {{ font-size: 36px; flex-shrink: 0; color: {accentColor}; opacity: 0.9; }}
  .header-meta h1 {{ font-size: 24px; font-weight: 800; color: {accentColor}; text-transform: uppercase; letter-spacing: -0.5px; margin-bottom: 4px; }}
  .header-meta p  {{ font-size: 12px; color: #475569; font-weight: 600; letter-spacing: 0.5px; }}
  .header-logo {{ margin-left: auto; font-size: 11px; color: #64748b; text-align: right; line-height: 1.6; }}
  .official-seal {{ font-weight: 700; color: {accentColor}; font-size: 14px; text-transform: uppercase; border: 1.5px solid {accentColor}; padding: 4px 8px; border-radius: 4px; display: inline-block; margin-top: 8px; }}

  /* ── Stats Footer Bar ── */
  .stats-footer-bar {{ display: flex; gap: 20px; margin-top: 40px; border-top: 2px solid {accentColor}; padding: 20px 0; }}
  .stat-item {{ flex: 1; }}
  .stat-label {{ display: block; font-size: 10px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }}
  .stat-value {{ font-size: 13px; font-weight: 600; color: #0f172a; }}

  /* ── Table ── */
  .table-wrapper {{ margin-bottom: 40px; }}
  .table-header {{ padding-bottom: 12px; margin-bottom: 18px; border-bottom: 1.5px solid #e2e8f0;
                  font-size: 13px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 0.5px; }}
  table {{ width: 100%; border-collapse: collapse; border: 1px solid #e2e8f0; border-radius: 6px; overflow: hidden; }}
  thead tr {{ background: {accentColor}; color: #fff; }}
  thead th {{ padding: 14px 12px; text-align: {(isAr ? "right" : "left")}; font-size: 10.5px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; }}
  tbody tr {{ border-bottom: 1px solid #f1f5f9; }}
  tbody tr:nth-child(even) {{ background: #f8fafc; }}
  tbody td {{ padding: 12px; font-size: 11px; color: #334155; }}

  /* ── Summary Section ── */
  .summary-section {{ margin-top: 50px; page-break-inside: avoid; border-top: 1px solid #e2e8f0; padding-top: 30px; }}
  .summary-title {{ font-size: 14px; font-weight: 800; color: {accentColor}; text-transform: uppercase; margin-bottom: 20px; letter-spacing: 0.5px; }}
  .summary-table {{ width: 100%; max-width: 450px; margin: 0 auto; border: 1px solid #e2e8f0; }}
  .summary-table tr {{ border-bottom: 1px solid #f1f5f9; }}
  .summary-table td {{ padding: 12px 15px; font-size: 11.5px; }}
  .summary-table td:first-child {{ font-weight: 700; color: #64748b; text-transform: uppercase; background: #f8fafc; width: 65%; }}
  .summary-table td:last-child {{ font-weight: 800; color: #0f172a; text-align: center; font-size: 14px; }}

  /* ── Footer ── */
  .footer {{ text-align: center; color: #94a3b8; font-size: 10px; padding-top: 30px; margin-top: 50px; border-top: 1px dotted #e2e8f0; letter-spacing: 0.5px; }}

  @media print {{
    body {{ background: #fff; }}
    .page {{ padding: 0; }}
    .header {{ margin-bottom: 40px; }}
    .summary-section {{ border-top-color: #cbd5e1; }}
  }}
</style>
</head>
<body>
<div class='page'>

  <div class='header'>
    <div class='header-icon'>{iconEmoji}</div>
    <div class='header-meta'>
      <h1>{reportTitle}</h1>
      <p>Immunization &amp; Community Management System (ICMS)</p>
    </div>
    <div class='header-logo'>
      <div style='font-weight: 800; color: {accentColor}; font-size: 16px; margin-bottom: 2px;'>ICMS</div>
      <div class='official-seal'>{lblOfficial}</div>
    </div>
  </div>

  {bodyContent}

  {summaryHtml}

  {statsBar}

  <div class='footer'>
    {lblFooter} &nbsp;·&nbsp; {data.GeneratedAt} &nbsp;·&nbsp; Confidential &nbsp;·&nbsp; ID: {data.TotalRecords}-{DateTime.UtcNow.Ticks % 10000}
  </div>

</div>
</body>
</html>";
        }

        private static string BuildSummaryCards(Dictionary<string, string> stats, string accentColor = "#2586C7", string sectionTitle = "Summary Statistics")
        {
            if (stats.Count == 0) return string.Empty;

            var rows = new StringBuilder();
            foreach (var kv in stats)
                rows.Append($"<tr><td>{kv.Key}</td><td>{kv.Value}</td></tr>");

            return $@"<div class='summary-section'>
              <div class='summary-title'>{sectionTitle}</div>
              <table class='summary-table'>{rows}</table>
            </div>";
        }

        public static string BuildDataTable(List<string> headers, List<ReportRow> rows, string sectionTitle = "Report Data")
        {
            var thead = new StringBuilder();
            foreach (var h in headers) thead.Append($"<th>{h}</th>");

            var tbody = new StringBuilder();
            if (rows.Count == 0)
            {
                tbody.Append($"<tr><td colspan='{headers.Count}' style='text-align:center;padding:24px;color:#9ca3af;'>No records found for this period.</td></tr>");
            }
            else
            {
                foreach (var row in rows)
                {
                    tbody.Append("<tr>");
                    foreach (var h in headers)
                        tbody.Append($"<td>{row.Columns.GetValueOrDefault(h) ?? "-"}</td>");
                    tbody.Append("</tr>");
                }
            }

            return $@"<div class='table-wrapper'>
              <div class='table-header'>{sectionTitle} ({rows.Count})</div>
              <table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>
            </div>";
        }

        /// <summary>Simple darkening: reduces hex by ~20%.</summary>
        private static string Darken(string hex)
        {
            if (hex.StartsWith('#') && hex.Length == 7)
            {
                try
                {
                    int r = Math.Max(0, Convert.ToInt32(hex[1..3], 16) - 40);
                    int g = Math.Max(0, Convert.ToInt32(hex[3..5], 16) - 40);
                    int b = Math.Max(0, Convert.ToInt32(hex[5..7], 16) - 40);
                    return $"#{r:X2}{g:X2}{b:X2}";
                }
                catch
                {
                    // Fallback to original color if hex processing fails
                }
            }
            return hex;
        }
    }
}
