using ICMS.Application.DTOs.Reports;
using System.Text;

namespace ICMS.Infrastructure.Reports.Templates
{
    /// <summary>
    /// Shared HTML rendering helper used by all report template renderers.
    /// Provides a professional, print-ready layout with ICMS branding.
    /// </summary>
    public static class ReportHtmlBase
    {
        public static string Wrap(string accentColor, string reportTitle, string iconEmoji, ReportData data,
            string bodyContent)
        {
            var isAr = data.Lang.StartsWith("ar", StringComparison.OrdinalIgnoreCase);
            var dir = isAr ? "rtl" : "ltr";
            var fontUrl = isAr
                ? "https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700&display=swap"
                : "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap";
            var fontFamily = isAr ? "'Cairo', sans-serif" : "'Inter', sans-serif";

            // Show a single date for daily reports; a range for multi-day reports
            var periodDisplay = data.StartDate == data.EndDate
                ? data.StartDate.ToString("yyyy-MM-dd")
                : $"{data.StartDate:yyyy-MM-dd} → {data.EndDate:yyyy-MM-dd}";

            var lblPeriod = isAr ? "فترة التقرير" : "Report Period";
            var lblRecords = isAr ? "إجمالي السجلات" : "Total Records";
            var lblGenAt = isAr ? "وقت الإنشاء" : "Generated At";
            var lblOfficial = isAr ? "تقرير رسمي" : "Official Report";
            var lblFooter = isAr ? "أُنشئ تلقائياً بواسطة ICMS" : "Automatically generated by ICMS";

            var statsBar = $@"
                <div class='stats-footer-bar'>
                    <div class='stat-item'><span class='stat-label'>{lblPeriod}</span><span class='stat-value'>{periodDisplay}</span></div>
                    <div class='stat-item'><span class='stat-label'>{lblGenAt}</span><span class='stat-value'>{data.GeneratedAt}</span></div>
                </div>";

            return $@"<!DOCTYPE html>
<html lang='{data.Lang}' dir='{dir}'>
<head>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0'>
<title>{reportTitle} — ICMS Report</title>
<style>
  @import url('{fontUrl}');

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: {fontFamily}; background: #fff; color: #1e2a3b; font-size: 11px; line-height: 1.5; }}
  .page {{ max-width: 1000px; margin: 0 auto; padding: 40px; }}

  /* ── Header ── */
  .header {{ border-bottom: 2.5px solid {accentColor}; padding-bottom: 20px; margin-bottom: 30px;
             display: flex; align-items: center; gap: 25px; }}
  .header-icon {{ font-size: 36px; flex-shrink: 0; color: {accentColor}; opacity: 0.9; }}
  .header-meta h1 {{ font-size: 24px; font-weight: 800; color: {accentColor}; text-transform: uppercase; letter-spacing: -0.5px; margin-bottom: 4px; }}
  .header-meta p  {{ font-size: 12px; color: #475569; font-weight: 600; letter-spacing: 0.5px; }}
  .header-logo {{ margin-left: auto; font-size: 11px; color: #64748b; text-align: right; line-height: 1.6; }}

  /* ── Report Info Grid (Formal Header Metadata) ── */
  .report-info-grid {{ display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 25px; 
                        padding-bottom: 15px; border-bottom: 1.5px solid #e2e8f0; {(isAr ? "flex-direction: row-reverse;" : "")} }}
  .info-group {{ display: flex; flex-direction: column; gap: 4px; }}
  .info-label {{ font-size: 9px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }}
  .info-value {{ font-size: 12px; font-weight: 700; color: #0f172a; }}
  .info-value.period {{ color: {accentColor}; font-size: 13px; }}

  /* ── Table ── */
  .table-wrapper {{ margin-bottom: 40px; }}
  .table-header {{ padding-bottom: 12px; margin-bottom: 18px; border-bottom: 1.5px solid #e2e8f0;
                  font-size: 13px; font-weight: 700; color: #0f172a; text-transform: uppercase; letter-spacing: 0.5px; }}
  table {{ width: 100%; border-collapse: collapse; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); }}
  thead tr {{ background: {accentColor}; color: #fff; }}
  thead th {{ padding: 14px 12px; text-align: {(isAr ? "right" : "left")}; font-size: 10.5px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; }}
  tbody tr {{ border-bottom: 1px solid #f1f5f9; }}
  tbody tr:nth-child(even) {{ background: #f8fafc; }}
  tbody td {{ padding: 12px; font-size: 11px; color: #334155; }}

  /* ── Table Summary (Formal Ledger Rows - Only at the end) ── */
  .summary-body tr, .summary-body tr:nth-child(even) {{ background: linear-gradient(135deg, {accentColor} 0%, {Darken(accentColor)} 100%) !important; color: #fff !important; page-break-inside: avoid; }}
  .summary-body td {{ padding: 12px 18px; border-bottom: 1px solid rgba(255,255,255,0.1); font-size: 11px; color: #fff !important; }}
  .summary-body tr:last-child td {{ border-bottom: none; }}
  
  .tfoot-label-cell {{ font-weight: 800; text-transform: uppercase; letter-spacing: 1.5px; font-size: 9.5px; color: #fff !important; }}
  .tfoot-value-cell {{ font-weight: 800; font-size: 15px; text-align: center; background: rgba(0, 0, 0, 0.15); width: 130px; color: #fff !important; }}
  .tfoot-value-cell.status-ready {{ color: #fef08a !important; }}
  
  /* Report Summary Block specifically */
  .summary-block-table tbody tr {{ background: transparent !important; }}
  .summary-block-table tbody tr:nth-child(even) {{ background: transparent !important; }}

  /* ── Footer ── */
  .footer {{ text-align: center; color: #94a3b8; font-size: 10px; padding-top: 30px; margin-top: 50px; border-top: 1px dotted #e2e8f0; letter-spacing: 0.5px; }}

  @media print {{
    body {{ background: #fff; }}
    .page {{ padding: 0; }}
    .header {{ margin-bottom: 40px; }}
  }}
</style>
</head>
<body>
<div class='page'>

  <div class='header'>
    <div class='header-icon'>{iconEmoji}</div>
    <div class='header-meta'>
      <h1>{reportTitle}</h1>
      <p>Immunization and Care Management System (ICMS)</p>
    </div>
    <div class='header-logo'>
      <div style='font-weight: 800; color: {accentColor}; font-size: 16px; margin-bottom: 2px;'>ICMS</div>
    </div>
  </div>

  <div class='report-info-grid'>
    <div class='info-group'>
      <span class='info-label'>{lblPeriod}</span>
      <span class='info-value period'>{periodDisplay}</span>
    </div>
    <div class='info-group' style='text-align: {(isAr ? "left" : "right")};'>
      <span class='info-label'>{lblGenAt}</span>
      <span class='info-value'>{data.GeneratedAt}</span>
    </div>
  </div>

  {bodyContent}

  <div class='footer'>
    {lblFooter} &nbsp;·&nbsp; {data.GeneratedAt} &nbsp;·&nbsp; Confidential &nbsp;·&nbsp; ID: {data.TotalRecords}-{DateTime.UtcNow.Ticks % 10000}
  </div>

</div>
</body>
</html>";
        }

        public static string BuildDataTable(List<string> headers, List<ReportRow> rows, string sectionTitle,
            string accentColor, Dictionary<string, string>? summaryStats = null, bool isAr = false)
        {
            var thead = new StringBuilder();
            foreach (var h in headers) thead.Append($"<th>{h}</th>");

            var tbody = new StringBuilder();
            if (rows.Count == 0)
            {
                tbody.Append(
                    $"<tr><td colspan='{headers.Count}' style='text-align:center;padding:24px;color:#9ca3af;'>No records found for this period.</td></tr>");
            }
            else
            {
                foreach (var row in rows)
                {
                    tbody.Append("<tr>");
                    foreach (var h in headers)
                        tbody.Append($"<td>{row.Columns.GetValueOrDefault(h) ?? "-"}</td>");
                    tbody.Append("</tr>");
                }
            }

            var tfoot = BuildSummaryFooter(summaryStats!, headers.Count, isAr);

            return $@"<div class='table-wrapper'>
              <div class='table-header'>{sectionTitle} ({rows.Count})</div>
              <table>
                <thead><tr>{thead}</tr></thead>
                <tbody>{tbody}</tbody>
                {tfoot}
              </table>
            </div>";
        }

        private static string BuildSummaryFooter(Dictionary<string, string> stats, int colCount, bool isAr)
        {
            if (stats == null || stats.Count == 0) return string.Empty;

            var rows = new StringBuilder();
            foreach (var kv in stats)
            {
                var isStatus = kv.Value.Equals("Ready", StringComparison.OrdinalIgnoreCase) || 
                               kv.Value.Equals("Completed", StringComparison.OrdinalIgnoreCase) ||
                               kv.Value.Equals("جاهز", StringComparison.OrdinalIgnoreCase);

                rows.Append($@"
                    <tr>
                        <td colspan='{colCount - 1}' class='tfoot-label-cell'>{kv.Key}</td>
                        <td class='tfoot-value-cell {(isStatus ? "status-ready" : "")}'>{kv.Value}</td>
                    </tr>");
            }

            return $@"<tbody class='summary-body'>{rows}</tbody>";
        }

        public static string BuildSummaryStatsBlock(Dictionary<string, string> stats, string accentColor, bool isAr)
        {
            if (stats == null || stats.Count == 0) return string.Empty;

            var rows = new StringBuilder();
            foreach (var kv in stats)
            {
                rows.Append($@"
                    <tr>
                        <td class='tfoot-label-cell' style='padding: 10px 14px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px;'>{kv.Key}</td>
                        <td style='padding: 10px 14px; font-weight: 800; font-size: 13px; text-align: center; background: rgba(0, 0, 0, 0.15); width: 150px; color: #fff;'>{kv.Value}</td>
                    </tr>");
            }

            var sectionTitle = isAr ? "ملخص التقرير" : "Report Summary";

            return $@"<div class='table-wrapper' style='max-width: 400px; margin-top: 30px; page-break-inside: avoid;'>
              <div class='table-header'>{sectionTitle}</div>
              <table class='summary-block-table' style='border-radius: 6px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.05);'>
                <tbody style='background: linear-gradient(135deg, {accentColor} 0%, {Darken(accentColor)} 100%); color: #fff;'>
                  {rows}
                </tbody>
              </table>
            </div>";
        }

        private static string Darken(string hex)
        {
            if (hex.StartsWith('#') && hex.Length == 7)
            {
                try
                {
                    int r = Math.Max(0, Convert.ToInt32(hex[1..3], 16) - 40);
                    int g = Math.Max(0, Convert.ToInt32(hex[3..5], 16) - 40);
                    int b = Math.Max(0, Convert.ToInt32(hex[5..7], 16) - 40);
                    return $"#{r:X2}{g:X2}{b:X2}";
                }
                catch
                {
                    // Fallback to original color if hex processing fails
                }
            }

            return hex;
        }
    }
}
